// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/riden/CaptainClean.tsx": () => import("../components/mockups/riden/CaptainClean.tsx"),
  "./components/mockups/riden/CaptainMidnight.tsx": () => import("../components/mockups/riden/CaptainMidnight.tsx"),
  "./components/mockups/riden/PassengerClean.tsx": () => import("../components/mockups/riden/PassengerClean.tsx"),
  "./components/mockups/riden/PassengerMidnight.tsx": () => import("../components/mockups/riden/PassengerMidnight.tsx")
};
